# Generated by Django 3.2 on 2021-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('temperature_enabled', models.BooleanField()),
                ('humidity_enabled', models.BooleanField()),
                ('light_enabled', models.BooleanField()),
                ('temperature_setpoint', models.IntegerField()),
                ('humidity_setpoint', models.IntegerField()),
                ('light_setpoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('ripeness', models.CharField(max_length=50)),
                ('last_watered', models.DateField(auto_now=True)),
                ('watering_interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('notify', models.BooleanField()),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
